version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "8085:15672"
            - "5672:5672"
        volumes:
            - ./rabbitmq/docker/enabled_plugins:/etc/rabbitmq/enabled_plugins